### ISSUE TITLE
misplaced // +build line

### ISSUE THREAD

**Issue by rsc** [aletheia7/sd#1]
Hi. I've been surveying `// +build` usage in the Go ecosystem, and I noticed that in [s.go](https://github.com/aletheia7/sd/blob/1af8ca8777a84d187243e7007ecb2d048f4f341f/s.go), the line:

    // +build linux,cgo

is inside a C /* */ comment. The line will be ignored there; it must come before the /* */ comment, followed by a blank line (important!).

Also, the ",cgo" is implied by the import "C" in the file, so you can use just `// +build linux`.

Also, the blank line between the C /* */ comment and the package line is keeping the big comment from being treated as package documentation. You probably want to remove that blank line.

Best,
Russ

**Comment by aletheia7** [comment]
All of your changes have been made.

Thank you.

Also, Thank you for making Go. You and your team are doing a fantastic job.
